#!/usr/bin/env bash
# claw - Launch scoped Claude worktree sessions for {{project_name}} tasks
# Generated by ClaudeClaw setup wizard
set -euo pipefail

TARGET_DIR="{{target_dir}}"

# ---------------------------------------------------------------------------
# Permission building blocks
# ---------------------------------------------------------------------------
TOOLS_READ="Read,Glob,Grep,Bash(ls:*),Bash(find:*)"
TOOLS_EDIT="Read,Write,Edit,Glob,Grep"
TOOLS_TEST="{{tools_test}}"
TOOLS_GIT_SAFE="Bash(git status:*),Bash(git diff:*),Bash(git log:*),Bash(git add:*),Bash(git commit:*),Bash(git branch:*)"
TOOLS_GIT_PUSH="Bash(git push:*)"
TOOLS_DENY="{{tools_deny}}"

# ---------------------------------------------------------------------------
# Presets: compose building blocks per task type
# ---------------------------------------------------------------------------
preset_tools() {
    local raw
    case "$1" in
        analyze)     raw="$TOOLS_READ" ;;
        fix)         raw="$TOOLS_EDIT,$TOOLS_TEST,$TOOLS_READ" ;;
        fix-commit)  raw="$TOOLS_EDIT,$TOOLS_TEST,$TOOLS_READ,$TOOLS_GIT_SAFE" ;;
        full)        raw="$TOOLS_EDIT,$TOOLS_TEST,$TOOLS_READ,$TOOLS_GIT_SAFE,$TOOLS_GIT_PUSH" ;;
        *)           echo ""; return 1 ;;
    esac
    # Deduplicate while preserving order
    echo "$raw" | tr ',' '\n' | awk '!seen[$0]++' | paste -sd ',' -
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------
usage() {
    cat <<'EOF'
Usage: claw <command> [options]

Commands:
  run <preset> <prompt>       Launch worktree with scoped permissions
  run <preset> -f <file>      Read prompt from spec file
  presets                     List available permission presets
  worktrees                   List active worktrees
  clean                       Remove worktrees with no uncommitted changes

Presets:
  analyze      Read-only exploration (no writes)
  fix          Edit + test (no git)
  fix-commit   Edit + test + commit (no push)
  full         Everything except destructive git ops

Options:
  --model <model>      Override model (default: opus)
  --no-worktree        Run in-place (no worktree branch)
  --dry-run            Show the command without executing
  --prompt-prefix <p>  Prepend text to the generated prompt
  -f <file>            Read task spec from file

Examples:
  claw run fix-commit -f docs/bugs/BUG1.md
  claw run analyze "How does the main module work?"
  claw run fix "Add input validation to the API endpoint"
  claw run fix-commit --dry-run -f docs/epics/STORY1.md
EOF
}

cmd_presets() {
    echo "Available presets:"
    echo ""
    for key in analyze fix fix-commit full; do
        printf "  %-12s " "$key"
        preset_tools "$key" | tr ',' '\n' | head -1
        preset_tools "$key" | tr ',' '\n' | tail -n +2 | sed 's/^/               /'
        echo ""
    done
}

cmd_worktrees() {
    cd "$TARGET_DIR" && git worktree list
}

cmd_clean() {
    cd "$TARGET_DIR" || exit 1

    git worktree list --porcelain | grep "^worktree " | awk '{print $2}' | \
        grep "/.claude/worktrees/" | while read -r wt; do
            local name
            name=$(basename "$wt")
            local branch
            branch=$(cd "$wt" && git branch --show-current 2>/dev/null || echo "unknown")
            local changes
            changes=$(cd "$wt" && git status --porcelain 2>/dev/null | wc -l | tr -d ' ')

            if [ "$changes" = "0" ]; then
                echo "  Removing: $name ($branch)"
                git worktree remove "$wt" 2>/dev/null || true
                git branch -D "$branch" 2>/dev/null || true
            else
                echo "  Skipping: $name ($changes uncommitted files)"
            fi
        done

    echo "Done."
}

cmd_run() {
    local preset="${1:-}"
    if [[ -z "$preset" ]]; then
        echo "Error: preset required. Use: analyze, fix, fix-commit, full" >&2
        exit 1
    fi
    shift

    local allowed
    allowed=$(preset_tools "$preset") || {
        echo "Error: unknown preset '$preset'. Use: analyze, fix, fix-commit, full" >&2
        exit 1
    }

    local model="opus"
    local use_worktree=true
    local dry_run=false
    local prompt=""
    local prompt_prefix=""

    # Parse options
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -f|--file)
                if [[ -z "${2:-}" ]]; then
                    echo "Error: -f requires a file path" >&2; exit 1
                fi
                local spec_file="$2"; shift 2
                prompt="Read $spec_file and execute the task described. Follow TDD: write failing tests first, then implement. Run the full test suite with '{{test_suite_command}}'. Show what you did."
                ;;
            --model)        model="$2"; shift 2 ;;
            --no-worktree)  use_worktree=false; shift ;;
            --dry-run)      dry_run=true; shift ;;
            --prompt-prefix) prompt_prefix="$2"; shift 2 ;;
            -*)
                echo "Error: unknown option '$1'" >&2; exit 1 ;;
            *)
                prompt="$1"; shift ;;
        esac
    done

    if [[ -z "$prompt" ]]; then
        echo "Error: no prompt or spec file provided" >&2
        usage; exit 1
    fi

    # Prepend prefix if given
    if [[ -n "$prompt_prefix" ]]; then
        prompt="${prompt_prefix} ${prompt}"
    fi

    # Build command parts
    # CLAUDECODE= ANTHROPIC_API_KEY= prevents nesting issues
    local -a cmd_parts=(
        "cd" "$TARGET_DIR" "&&"
        "echo" "$(printf '%q' "$prompt")" "|"
        "CLAUDECODE=" "ANTHROPIC_API_KEY="
        "claude"
    )

    if $use_worktree; then
        cmd_parts+=("-w")
    fi

    cmd_parts+=(
        "-p"
        "--model" "$model"
        "--allowedTools" "'${allowed}'"
        "--disallowedTools" "'${TOOLS_DENY}'"
    )

    local cmd_str="${cmd_parts[*]}"

    if $dry_run; then
        echo "Preset:    $preset"
        echo "Model:     $model"
        echo "Worktree:  $use_worktree"
        echo "Allowed:   $allowed"
        echo "Denied:    $TOOLS_DENY"
        echo "Prompt:    ${prompt:0:120}..."
        echo ""
        echo "Command:"
        echo "  $cmd_str"
        return
    fi

    echo "=== claw run ==="
    echo "Preset:    $preset"
    echo "Model:     $model"
    echo "Worktree:  $use_worktree"
    echo "Prompt:    ${prompt:0:120}..."
    echo "================"
    echo ""

    eval "$cmd_str"
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
case "${1:-}" in
    run)        shift; cmd_run "$@" ;;
    presets)    cmd_presets ;;
    worktrees)  cmd_worktrees ;;
    clean)      cmd_clean ;;
    -h|--help)  usage ;;
    "")         usage ;;
    *)          echo "Error: unknown command '$1'" >&2; usage; exit 1 ;;
esac
